apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: metropolitan-prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: MariaDB
    type: mysql
    uid: metropolitan-mariadb
    access: proxy
    url: database:3306
    database: template_db
    user: root
    jsonData:
      maxOpenConns: 2
      maxIdleConns: 2
      connMaxLifetime: 14400
    secureJsonData:
      password: ${DB_PASSWORD}
    editable: true
